# Welcome to Serverless!
service: serverless-example
app: product-api


provider:
  name: aws
  runtime: nodejs14.17. 4
  stage: dev
  region: us-east-1

functions:
  migrationUp:
    UpAllMigration: handler.UpAllMigration
plugins:
  - serverless-offline
  - serverless-dotenv-plugin